# Generated by Django 3.0.6 on 2020-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tagline',
            field=models.CharField(max_length=300),
        ),
    ]
