# Generated by Django 3.0.6 on 2020-05-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200517_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='blog_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
