# Generated by Django 3.0.6 on 2020-05-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bodytext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
