# Generated by Django 3.0.6 on 2020-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='This is a Short Description', max_length=200),
            preserve_default=False,
        ),
    ]
