# Generated by Django 3.0.6 on 2020-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200510_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
