# Generated by Django 3.0.6 on 2020-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(),
        ),
    ]
